apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ymatev-demo-app
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: templates
    repoURL: 'https://github.com/yulian-matev/istio-tryout-deployment.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
