---
- name: Deploy to K8s Cluster
  hosts: localhost
  become: true

  tasks:
    - name: Deploy Pod
      shell: |
        kubectl apply -f devops-blue-deployment.yml

    - name: Deploy Service
      shell: |
        kubectl apply -f devops-blue-service.yml
