---
- name: Install ArgoCD to K8s Cluster
  hosts: localhost
  become: true

  tasks:
    - name: Create namespace ArgoCD
      shell: |
        kubectl create namespace argocd

    - name: Install Argo CD
      shell: |
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
