version: "3"
services:

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    networks:
      - internal

  php-svc:
    build:
      context: php/
      dockerfile: Dockerfile
    networks:
      - internal

networks:
  internal:
    driver: bridge
