name: on-push
run-name: on-push
on: [push]
jobs:

  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  calc-docker-image-tag:
    needs: [editorconfig]
    runs-on: ubuntu-latest
    outputs:
      img-tag-out: ${{ steps.tag_calc_step.outputs.MY_IMG_TAG }}
    steps:
      - uses: actions/checkout@v4
      -
        name: Calculate docker image tag
        id: tag_calc_step
        run: |
          USER_VERSION=$(perl -n -e'/"SERVICE_VER",\s+.*"(.*)"/ && print $1' ./src/micro-svc/php/api.php)
          MY_TAG=${GITHUB_RUN_NUMBER}-${USER_VERSION}-${GITHUB_SHA::6}
          echo "Calculate docker image tag: ${MY_TAG}"
          echo "MY_IMG_TAG=${MY_TAG}" >> $GITHUB_OUTPUT

  generate-deployment:
    needs: [calc-docker-image-tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate deployment files
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          IMG_TAG: ${{needs.calc-docker-image-tag.outputs.img-tag-out}}
          DEPL_REPO: istio-tryout-deployment
        run: |
          git clone https://yulian-matev:$GITHUB_TOKEN@github.com/yulian-matev/${DEPL_REPO}    # This works

          cd ${DEPL_REPO}/templates
          echo "pwd: " && pwd
          git config user.name "github-action"
          git config user.email "noreply@devoops.com"

          cp ../../deployment-template/*.yml .

          # global inplace replacement of value __TAG__ with env var IMG_TAG content
          #
          #   -p                assume loop like -n but print line also, like sed
          #   -i[extension]     edit <> files in place (makes backup if extension supplied)
          #   -e program        one line of program
          perl -pi -e 's/__TAG__/$ENV{IMG_TAG}/g' *.yml

          git add *.yml
          git commit -m "Create deployment for tag $IMG_TAG"
          git push
