name: on-push
run-name: on-push
on: [push]
jobs:

  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  calc-docker-image-tag:
    needs: [editorconfig]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Calculate docker image tag
        run: |
          USER_VERSION=$(perl -n -e'/"SERVICE_VER",\s+.*"(.*)"/ && print $1' ./src/micro-svc/php/api.php)
          MY_TAG=${GITHUB_RUN_NUMBER}-${USER_VERSION}-${GITHUB_SHA::6}
          echo "Calculate docker image tag: ${MY_TAG}"
          echo "MY_IMG_TAG=${MY_TAG}" >> $GITHUB_OUTPUT
          perl -p -e 's/xxxxxxx/${MY_TAG}/g' ./src/micro-svc/php/api.php

  generate-deployment:
    needs: [calc-docker-image-tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate deployment files
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          DEPL_REPO: istio-tryout-deployment
        run: |
          git clone https://yulian-matev:$GITHUB_TOKEN@github.com/yulian-matev/${DEPL_REPO}    # This works

          cd ${DEPL_REPO}
          echo "pwd: " && pwd
          git config user.name "github-action"
          git config user.email "noreply@devoops.com"

          #cat ../README.md > text.txt
          #echo "this is test" >> text.txt

          cp ../deployment-template/*.yml .

          echo "ls -l" && ls -l
          git add *.yml

          git commit -m "Create deployment for tag"

          git push
