name: Verify after each push
run-name: Verify after each push
on: [push]
jobs:

  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  code-checker-black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

  php-check-syntax:
    needs: editorconfig
    runs-on:  ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run PHP lint
        uses: StephaneBour/actions-php-lint@8.2
        with:
          dir: './src'

  markdown-checker:
    needs: editorconfig
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run marksown checker
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          config: './.github/.markdownlint.yml'
          globs: '**/*.md'
