name: on-push
run-name: on-push
on: [push]
jobs:

  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  generate-deployment:
    needs: [editorconfig]
    runs-on: ubuntu-latest
    steps:
      - name: Generate deployment files
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          DEPL_REPO: istio-tryout-deployment
        run: |
          git clone https://yulian-matev:$GITHUB_TOKEN@github.com/yulian-matev/${DEPL_REPO}    # This works

          cd ${DEPL_REPO}
          echo "pwd: " && pwd
          git config user.name "github-action"
          git config user.email "noreply@devoops.com"

          echo "this is test" > text.txt
          echo "ls -l" && ls -l
          git add text.txt
          git commmit -m "Create deployment for tag"

          git push
