name: on-feature-push
run-name: on-feature-push
on:
  push:
    branches:
      - 'feat-**'
jobs:

  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  php-check-syntax:
    needs: editorconfig
    runs-on:  ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run PHP lint
        uses: StephaneBour/actions-php-lint@8.2
        with:
          dir: './src'

  secret-checker:
    needs: [editorconfig]
    runs-on: ubuntu-latest
    name: Vulnerabilities check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for vulnerabilities
        id: checks
        uses: maddygoround/secretduty@v1.3
      - name: Get results of scan
        run: echo "Scan Results - ${{ steps.checks.outputs.result }}"

  gitleaks-scan:
    needs: editorconfig
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
#         GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts

  sonarcloud:
    needs: editorconfig
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  snyk-check:
    needs: editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        with:
          args: --severity-threshold=high
#          args: --file=app/requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}




  # calc-docker-image-tag:
  #   needs: [editorconfig, secret-checker]
  #   runs-on: ubuntu-latest
  #   outputs:
  #     img-tag-out: ${{ steps.tag_calc_step.outputs.MY_IMG_TAG }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     -
  #       name: Calculate docker image tag
  #       id: tag_calc_step
  #       run: |
  #         USER_VERSION=$(perl -n -e'/"SERVICE_VER",\s+.*"(.*)"/ && print $1' ./src/micro-svc/php/api.php)
  #         MY_TAG=${GITHUB_RUN_NUMBER}-${USER_VERSION}-${GITHUB_SHA::6}
  #         echo "Calculated docker image tag: ${MY_TAG}"
  #         echo "MY_IMG_TAG=${MY_TAG}" >> $GITHUB_OUTPUT

