name: on-push
run-name: on-push
on: [push]
jobs:

  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  generate-deployment:
    needs: [editorconfig]
    runs-on: ubuntu-latest
    steps:
      - name: Generate deployment files
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          git clone https://yulian-matev:$GITHUB_TOKEN@github.com/yulian-matev/istio-tryout-deployment    # This works

          find .
